name: bhoomima
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  photo_view: ^0.14.0
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.3
  geocoding: ^2.1.1
  connectivity_plus: ^6.0.1
  flutter_compass: ^0.8.0
  sensors_plus: ^6.1.1
  isar: ^3.1.0+1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  isar_flutter_libs: ^3.1.0+1
  share_plus: ^10.0.2
  archive: ^3.6.1
  url_launcher: ^6.3.0
  vector_math: ^2.1.4
  flutter_svg: ^2.0.10
  matrix_gesture_detector_pro: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/seed_vocab.json
    - assets/i18n/BM-55_parameters_seed.csv
    - assets/icons/
    - assets/seeds/BM-142_icons_catalog_seed.csv
